theme: jekyll-theme-minimal
plugins:
  - jekyll-sitemap
github:
  is_project_page: false
show_downloads: false
title: doDDD - Domain-driven Design in Dortmund 
description: Ein Ort zum Austausch über Domain-driven Design und Collaborative Modeling
